# Generated by Django 5.0.7 on 2025-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
