# Generated by Django 5.0.7 on 2025-06-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario',
        ),
    ]
