# Generated by Django 5.0.7 on 2025-06-10 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0012_alter_artista_tipo_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='scheduled_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data Agendada'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Envio'),
        ),
    ]
